# -*- coding: utf-8 -*-
"""country_profile_variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a5kYh7b4vQl2yNyfXX1zb168JxxDSGIw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/country_profile_variables.csv')
df

df.head(3)

"""* Country - Name of the country or territory
* Region - world region the country is located
"""

df.info()

df['Employment: Agriculture (% of employed)']

df.isnull().sum()

df.duplicated().sum()

import statistics as stat
import numpy as np

"""# Find average population of all country in year 2017."""

df['Population in thousands (2017)'].mean()

"""Find the middle values of population of all 229 countries"""

df['Population in thousands (2017)'].median()

"""Find out the mean and standard deviation of GDP PER CAPITA"""

df['GDP per capita (current US$)']

df['GDP per capita (current US$)'].mean()

df['GDP per capita (current US$)'].std()

"""From the entire dataset create a sample of 100 rows."""

sample_data = df.sample(n=5)
sample_data

"""# In random state we are using to lock the pattern of your data"""

sample_data = df.sample(n =20, random_state= 1)
sample_data

# Find the co-relation between GDP PER CAPTIA    AND URBAN POPULATION %

df ['Urban population (% of total population)']

correlation = df [['Urban population (% of total population)', 'GDP per capita (current US$)']].corr()
correlation

"""Find out the average % of seats held by women in national parliament"""

df['Seats held by women in national parliaments %'].mean()

"""Find out the relationship between "GDP Per Captia" And "Internet Usage" by using scatter Plot."""

import matplotlib.pyplot as plt
import seaborn as sns

df['Individuals using the Internet (per 100 inhabitants)']

sns.scatterplot(data = df,x = 'Individuals using the Internet (per 100 inhabitants)' , y = 'GDP per capita (current US$)')
plt.title('GDP Per Captia V/S Internet users')
plt.xlabel('Internet Users')
plt.ylabel('GDP per Captia')
plt.show()

"""Check outliers for all numerical columns in our data.

"""

col_list = list(df.columns)
col_list

for x in col_list:
  if df[x].dtype == 'object':
    continue
  plt.boxplot(df[x])
  plt.xlabel(x)
  plt.ylabel('Count')
  plt.show()

"""Plot a bar chart showing top 10 countries by GDP Per captia."""

# I want top 10 countries with highest GDP per Captia
# we will sort the data with respect to GDP per captia

top_10_countries = df.sort_values(by='GDP per capita (current US$)', ascending = False).head(10)
top_10_countries

plt.bar(top_10_countries['country'],top_10_countries['GDP per capita (current US$)'])
plt.title('Top 10 Highest GDP Countries (2017)')
plt.xticks(rotation = 45)
plt.ylabel('GDP')
plt.show()

