# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rAoNJDhcLWUrtB_2tDyffua_FxWxeyZG
"""

import numpy as np

ar1 = np.array([1,2,3,4,5]) # list /tuples
ar1

ar2 = np.array((1,2,3,4,5))
ar2

np.zeros([3,4])

np.random.random([3,4])

var1 = 20
var1 +2

"""eror : name
1. case senestive
2.  spelling mistak
3.  re excute source line of code
"""

np.full([3,4],10)

np.full([2,2],'a')

range(1,5)

for i in range(1,5):
  print(i)

list(range(1,5))

list(range(1,10,2))

np.arange(1,10,2) #array + range

list(range(1,10,2)) #start ,end(excluding) ,step(-1)
#from 1 till  10 skip  1 numbers in between

np.linspace(1,10,6)

4.6-2.8

np.linspace(1,20,9)

3.375-1

"""### Array Inspection"""

ar1 = np.arange(1,25)
ar1

ar1.size # no of element in array

ar1.dtype

# data types: python is dynamicaaly typed programing language --> python decides data type of variable
# sql : bigint / smallint (64,32)
# numbers: int / float
# character : strings / u

type(ar1)

ar1.ndim

ar2 = ar1.reshape(6,4)
ar2

ar2.ndim

ar1.reshape(3,8)

ar3 = ar1.reshape(3,2,4) # creating 3 arrays with 2 rows and 4 columns
ar3

ar3.ndim #number of dimensions

import numpy as np
ar1= np.array([[10,20],[30,40]])
ar1

np.sum(ar1)

np.sum(ar1,axis=0)

np.sum(ar1,axis=1)

print(np.mean(ar1))
print(np.median(ar1))
print(np.std(ar1))
print(np.var(ar1))
print(np.min(ar1))
print(np.max(ar1))
print(np.subtract(ar1,2))
print(np.add(ar1,2  ))
print(np.multiply(ar1,2))
print(np.divide(ar1,2))
print(np.log(20))

#slicing

list1 = [10,20,30,40,50]
print(list1[1:5])
print(np.array(list1).dtype)

#if i want to extract 20,30,40,50
list1[1:5]

list1[1:]

ar1 = np.array([10,20,30,40,50])
ar1[1:4]

ar1 = np.arange(1,25).reshape(6,4)
ar1

ar1 [2:4,1:3] # 2:4

ar1[2:6,0:4]

ar1 [2:,0:]

#if you want to take partiton in rows with all the columns
ar1[2:]

ar1 [2:,:]

#if you want to take partition in row with all the columns
ar1[2:]

#if you want to take few columns and all the rows
ar1[:,1:3]

# array manipulation

ar1 = np.array([[10,20],[30,40]])
ar2 = np.array([[10,20],[30,40]])
ar1+ar2

np.concatenate((ar1,ar2),axis=0)   #link (things) together in a chain or series.

np.row_stack((ar1,ar2))

np.vstack((ar1,ar2))

np.concatenate((ar1,ar2),axis=1)

np.column_stack((ar1,ar2))

np.hstack((ar1,ar2))

ar3 - np.hstack((ar1,ar2))

ar3 = np.hstack([ar1,ar2,ar1])
ar3

np.hsplit(ar3,3)

