# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PofHoIgLeyV0pWoH5ozW1k-NFC6X_dtz
"""

import pandas as pd
df1 = pd.read_csv('/content/Auto.csv')

df1.head(5) #by default top 5 observation

df1.head(10)

df1.tail(2)

df1.shape # no of rows * columns

df1.dtypes #it returns data types of columns
#numbers : int / float
# String : object

df1.isnull()

df1.isnull().sum()

df1.columns

df1.info()

df1.describe() #it will work on int/float data types

# [] --> List /Takes subset
#() --> tuples /methods(function)
# {} --> dict , sets

df1 ['mpg']

df1[['mpg','displacement','weight']]

df1['mpg'].mean()

df1['mpg'].min()

df1['mpg'].max()

df1[['mpg','displacement','weight']].max()

df1[['mpg','displacement','weight']].min()

df1[['mpg','displacement','weight']].mean()

df1[['mpg','displacement','weight']].median()

df1[['mpg','displacement','weight']].mode()

### how to crate new columns in dataset

df1.head(2)

##price , quantity --> sales

df1['acceleration']+df1['origin']

df1['new_col']=df1['acceleration']+df1['origin']
df1.head(2)

df1['new_col2'] = df1['acceleration']**2
df1.head(2)

df1['new_col3'] = 20
df1.head(2)

#### Cleaning the dataset
# 1. Horse power data type issue
# 2. Null values in columns
# data type conversions
# int --> float / float --> int (astype)

df1['col4'] =  df1['acceleration'].astype(int)
df1.head(2)

df1['Horse Power'].astype(int)

int('a')

df1['Horse Power'].isnull().sum()
# 0 indicates there are no null values available

df1['Horse Power'] = pd.to_numeric(df1['Horse Power'], errors = 'coerce' )
df1['Horse Power'].isnull().sum()
# coerce method we are forcing pandas to do the conversion and if the conversion is not possible replace them with Null
# wherever data type conversion is not possible we remove that string (creating blank/empty/null value)

df1['Horse Power'].dtype

# Treating missing values

df1.head(10)

df2 = df1.dropna()
df2.shape

# df1 = df1.dropna()
# df1.dropna(inplace = True) # commit changes

# how to replace blank values # mean / median / mode / ML algorithm to predict missing values

df1['mpg'].mean() # average : sum/total

df1['mpg'] = df1['mpg'].fillna(23.611) # fill na(null) values with 23.61
# df1['mpg'] = df1['mpg'].fillna(df1['mpg'].mean())
df1.head(6)

# how to remove unwanted columns
df1.drop('new_col1', axis = 1, inplace = True)
# axis = 1 --> to look for new_col1 in column names and remove that column --> inplace = True (commit your changes/ save the changes to df1)

df1.head(2)

df1.head(2)

df1.columns

df1.drop(['new_col2', 'new_col3','col4'], axis = 1, inplace = True)
df1.head(2)

# how to rename column in dataset
df1.rename({'Horse Power': 'horse_power'}, axis =1 , inplace = True)
df1.head(2)

# Key Error:
# 1. Spelling mistake
# 2. Case sensitive
# 3. column doesnt exist

df1.rename({0: 'horse_power'}, inplace = True) # by default axis will be set to 0
df1.head(2)

df1.columns

