# -*- coding: utf-8 -*-
"""StatsHandson_20June.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYmY6GiaLc7s-t9jvZBqvgDJ4BvaJ01q
"""

#Libraries - numpy, pandas, matplotlib and seaborn

"""#import the libraries"""

# !pip install numpy
# !pip install pandas
# !pip install matplotlib
# !pip install seaborn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Q. Create a dictionary with keys - name, age, salary with 5 entries(rows)."""

dictionary = {
    'name' : ['Poonam','Dani','Devan','Deepti','Trisha'],
    'Age' : [30,31,32,33,34],
    'Salary' : [100000,200000,1000000,300000,400000]
}

df = pd.DataFrame(dictionary) #converting the dictionary into a dataframe(table)

df

df.info()

#sum of all ages
df['Age'].sum()

"""Q. Find the average salary of all people in the df"""

df['Salary'].mean() #pandas

#numpy
np.mean(df['Salary'])

"""Q. Find the median of age column"""

df['Age'].median()

import statistics as st

st.mode(df['name']) #there is no mode in the column so the 1st encountered value will be taken as mode

df['name'].mode() #aranging in alphabetical order

"""#Sampling"""

#Probability - Random, Systematic, Stratified

#create a random array

arr = np.random.randint(1,200,50)

arr #data

#random sampling
r = np.random.choice(arr,20) #choosing 20 random numbers from the data
r

#Systematic - choose every 3 element in the sample
s = arr[::3]
s

#Stratified
even = arr[arr%2==0] #dividing the data into groups
odd = arr[arr%2!=0]

even

odd

x = np.random.choice(even,10)
y = np.random.choice(odd,10)

x

y

sample = np.concatenate((x,y))

sample

df

df['Gender'] = ['F','M','M','F','F']

df

#random
df.sample(3)

#systematic
df.iloc[::2,:] #[row_start:row_stop:row_step,col_start:col_stop:col_step]

#stratified
m = df[df['Gender']=='M']
m

f = df[df['Gender']=='F']
f

x = m.sample(1)
x

y = f.sample(2)
y

pd.concat([x,y],axis=0)

"""#Variation"""

range = df['Age'].max() - df['Age'].min()
range

plt.boxplot(df['Age']) #numeric continuous columns
plt.show()

d = [1,2,3,4,5,6,7,80]
plt.boxplot(d)
plt.show()

arr

np.percentile(arr,0)

np.percentile(arr,100)

np.percentile(arr,50)

np.median(arr)

arr

q1 = np.percentile(arr,25)
q1

q3 = np.percentile(arr,75)
q3

iqr = q3 - q1

iqr

ll = q1 - 1.5*iqr
ll

ul = q3 + 1.5*iqr
ul

arr

np.mean(arr)

np.std(arr) #magnitude of deviation

np.var(arr) #helpful to detect extreme values by squaring the deviaton

#how 2 variables are related to each other

df

df1 = df.select_dtypes(exclude = 'object') #selects only specific columns whose datatypes are considered
df1

df1.corr()

#heatmap - graph which is used to represent a matrix using a scale of colours
#which varies with the intensity of the value

sns.heatmap(df1.corr(),annot = True)
plt.show()

df = pd.read_csv('/content/cars - TA Poonam.csv') #read_excel('filename.xlsx')

df

#Bar chart - categorical column and numerical continuous column

sns.barplot(data = df,x = 'gear',y='mpg',ci = False) #which gear type is giving how much mileage
plt.show()

#which carb type is having the heaviest cars(wt)
sns.barplot(data = df,x='carb',y='wt',palette = 'Set2')
plt.show()

sns.lineplot(data = df,x = 'cyl',y='hp')
plt.show()

plt.plot(df['cyl'],df['hp'])
plt.show()

sns.scatterplot(data = df,x='mpg',y='hp') #relationship between 2 numerical variables
plt.show()

p = df.groupby('carb')['model'].count().reset_index()
p

plt.pie(p['model'],labels=p['carb'],autopct = '%1.2f%%')
plt.show()

sns.histplot(data = df,x='wt',bins = 15)
plt.show()

